[0.253s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 139, in build
    temp_symlinks = self._symlinks_in_build(args, setup_py_data)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 345, in _symlinks_in_build
    os.makedirs(os.path.dirname(dst), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/shivamss/colcon_ws/build/lawn_mower_control/resource/lawn_mower_control'
